### PR TITLE
Fix copy for assets dir introduced in playwright 1.32

### LINKED ISSUE #2: Merging does not work with Playwright 1.32.0
Merging reports generated with Playwright 1.32.0 produces an error if there's trace folder in the report.

```
Failed to merge reports: {"errno":-45,"code":"ENOTSUP","syscall":"copyfile","path":"/Users/<username>/web-e2e-tests/playwright-report-1/trace/assets","dest":"/Users/<username>/web-e2e-tests/playwright-report/trace/assets"}
```

Trace folder structure within html report has changed with 1.32.0 release and now contains sub-folder as well.

### PR DESCRIPTION
**Pull request by nil1511**
Fixes #2

### CODE REVIEW

**Comment by MindaugasMateika** [comment]
Can this be merged @anooprav7 and released?

**Comment by nil1511** [comment]
@MindaugasMateika I have published this package at `@nil1511/playwright-merge-html-reports` with this PR, as it was a blocker for me.

**Comment by costa-collibra** [comment]
@nil1511 can i get access to the published package with the fix in?

**Comment by nil1511** [comment]
It is public on https://www.npmjs.com/package/@nil1511/playwright-merge-html-reports
install that and replace the import 
eg. `require("playwright-merge-html-reports");` to `require("@nil1511/playwright-merge-html-reports");`

**Comment by costa-collibra** [comment]
@nil1511 thanks

**Comment by aaron-smits** [comment]
Thank you for your work @nil1511 !

**Comment by ajssd** [comment]
@anooprav7 When will this fix appear in a new released version, so we can move to Playwright 1.32.x without having to change dependencies?

**Review by anooprav7 — APPROVED** [review]
LGTM

**Comment by anooprav7** [comment]
This is published - https://www.npmjs.com/package/playwright-merge-html-reports/v/0.2.8

**Pull request merged**
